version: 2
services:
  backend:
    source: backend
    build:
      commands:
        - npm install
        - npm run build
    start:
      command: npm start
    environment:
      NODE_ENV: production
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3